# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

executors:
  # Define a parameterized executor which accepts two parameters to choose the python
  # version which will be used for the docker image and the tox actions.
  test:
    working_directory: ~/repo
    parameters:
      tag:
        type: string
        default: "3.7"
      pyenv:
        type: string
        default: "py37"
    docker:
      - image: circleci/python:<< parameters.tag >>
    environment:
      PYENV: << parameters.pyenv >>
  # Define the executor for the python semantic release.
  publisher:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.8

commands:
  # Reusable command to prepare the environment for testing.
  create_folders_and_venv:
    description: "Prepare everything."
    parameters:
      pyenv:
        type: string
    steps:
    # Checkout code.
    - checkout
    # Create test-result folder and the default output folder.
    - run:
        name: Create test result folder
        command: |
          mkdir test-results
          mkdir test-results/pytest
          mkdir -p output

    # Download and cache dependencies.
    - restore_cache:
        keys:
          - << parameters.pyenv >>-dependencies-
              {{checksum "requirements/dev-requirements.txt" }}
              {{ checksum "requirements/requirements.txt" }}
          # Fallback to using the latest cache if no exact match is found.
          - << parameters.pyenv >>-dependencies-

    # Create pyxml2pdf virtual environment.
    - run:
        name: Create virtual environment
        command: |
          python3 -m venv << parameters.pyenv >>
          source << parameters.pyenv >>/bin/activate
          pip install --upgrade pip

  # Reusable command to conduct actual testing.
  tox:
    description: "Perform tox testing."
    parameters:
      pyenv:
        type: string
    steps:

    # Install pyxml2pdf dependencies.
    - run:
        name: Install dependencies
        command: |
          python3 -m venv << parameters.pyenv >>
          source << parameters.pyenv >>/bin/activate
          pip install tox

    # Perform tox testing.
    - run:
        name: Perform tox testing
        command: |
          source << parameters.pyenv >>/bin/activate
          tox -e << parameters.pyenv >>

  # Reusable command to store the previously generated test results.
  store_results:
    description: "Store test results and artifacts."
    parameters:
      pyenv:
        type: string
    steps:
    # Store test results.
    - store_artifacts:
        path: test_results
        destination: test_results

    - store_test_results:
        path: test_results

    - save_cache:
        paths:
          - .tox/<< parameters.pyenv >>
        key: >-
          << parameters.pyenv >>-dependencies-
            {{checksum "requirements/dev-requirements.txt" }}
            {{ checksum "requirements/requirements.txt" }}

workflows:
  test_and_deploy:
    jobs:
      - test36
      - test37
      - test38
      - semantic-release:
          # Create 'release' job to create a release and publish it on GitHub.
          requires:
              - test36
              - test37
              - test38
          filters:
              branches:
                # This assures the job only being triggered on branch master.
                only: /master/

jobs:
  test36:
    executor:
      name: test
      tag: "3.6"
      pyenv: "py36"

    steps:
      - create_folders_and_venv:
          pyenv: ${PYENV}
      - tox:
          pyenv: ${PYENV}
      - store_results:
          pyenv: ${PYENV}

  test38:
    executor:
      name: test
      tag: "3.8"
      pyenv: "py38"

    steps:
      - create_folders_and_venv:
          pyenv: ${PYENV}

      # Install CI blocks dependencies.
      - run:
          name: Install Codacy and Codecov reporter
          command: |
            source ${PYENV}/bin/activate
            pip install --upgrade pip
            pip install -r requirements/requirements.txt
            pip install -r requirements/dev-requirements.txt
            pip install pytest pytest-cov codacy-coverage codecov

      # Set up Code Climate by downloading test reporter as a static binary.
      - run:
          name: Set up Code Climate test-reporter
          command: |
            curl -L 'https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64' > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      # Prepare for sending coverage reports to code climate.
      - run:
          name: Prepare code climate
          command: |
            source ${PYENV}/bin/activate
            ./cc-test-reporter before-build
            pytest -v --cov=. --junitxml=test_results/pytest/pytest.xml
            coverage xml
            ./cc-test-reporter after-build --coverage-input-type coverage.py \
                --exit-code $?
            python-codacy-coverage -r coverage.xml
            codecov
            mv coverage.xml ./test_results/pytest/
            coverage report -m > test_results/pytest/coverage.log
            mv ./output/ ./test_results/

      - store_results:
          pyenv: ${PYENV}

  test37:
    executor:
      name: test
      tag: "3.7"
      pyenv: "py37"

    steps:
      - create_folders_and_venv:
          pyenv: ${PYENV}
      - tox:
          pyenv: ${PYENV}
      - store_results:
          pyenv: ${PYENV}

  semantic-release:
    executor: publisher

    steps:
      # Checkout code
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            # Specify the unique identifier for the cache.
            - publisher-dependencies

      # Install dependencies.
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install python-semantic-release

      - save_cache:
          paths:
            - ./venv
          key: >-
            publisher-dependencies

      # Publish it!
      - run:
          name: Run semantic-release publish
          command: |
            source venv/bin/activate
            git config --global user.name "semantic-release (via CircleCI)"
            git config --global user.email "bjoern.ludwig@ptb.de"
            semantic-release publish
