# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
    - checkout

    # Create folder for test results.
    - run:
        name: create test result folder
        command: |
          mkdir test-reports

    # Download and cache dependencies.
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        # Fallback to using the latest cache if no exact match is found.
        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}

    # Set up Code Climate by downloading test reporter as a static binary
    - run:
        name: Setup Code Climate test-reporter
        command: |
          curl -L 'https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64' > ./cc-test-reporter
          chmod +x ./cc-test-reporter

    # Run coverage! We use pytest's test-runner (https://pytest.org)
    - run:
        name: run tests
        command: |
          . venv/bin/activate
        # notify Code Climate of a pending test report using `before-build`
          ./cc-test-reporter before-build
          pytest --cov=XMLToPDFConverter > pytest.xml
        # upload test report to Code Climate using `after-build`
          ./cc-test-reporter after-build --coverage-input-type pytest \
                   --exit-code $?

    # Store test results.
    - store_artifacts:
        path: pytest.xml
        destination: test-reports
